### ISSUE TITLE
Pre trained weights

### ISSUE THREAD

**Issue by IgorKasianenko** [Wanggcong/Spatial-Temporal-Re-identification#12]
Hello,
Thank you for sharing code for the paper. Could you please share weights on google drive or any other hosting that doesn't require baidu account? I'm having problems downloading it from outside of China.

**Comment by Wanggcong** [comment]
Will release the weights on google drive.

**Comment by Wanggcong** [comment]
You can download weights at this link: [google drive link](https://drive.google.com/drive/folders/1FIreE0pUGiqLzppzz_f7gHw0kaXZb1kC)
