### ISSUE TITLE
Gaussian smoothing on DukeMTMC-reID

### ISSUE THREAD

**Issue by saif86** [Wanggcong/Spatial-Temporal-Re-identification#15]
Hi. Why are you not applying Gaussian smoothing to the spatial temporal distribution in the "gen_st_nodel_duke.py" as it was applied in market data set. Also in market data set, smoothing of the distribution code is commented. Line 136 -139 in "gen_st_model_market.py"

**Comment by Wanggcong** [comment]
The Gaussian smoothing codes are moved to Line 177 of evaluate_st.py, i.e., [this line](https://github.com/Wanggcong/Spatial-Temporal-Re-identification/blob/02c45280e2b28d01f99c8a40c5bc579af615034f/evaluate_st.py#L177).

**Comment by saif86** [comment]
OK got it. Thanks.
