### ISSUE TITLE
How to compute the avarege precision?

### ISSUE THREAD

**Issue by jerryhitit** [Wanggcong/Spatial-Temporal-Re-identification#19]
I got confused by the ap computation process. what's the purpose of these lines?  Is there any other instructions about the ap computation?

[https://github.com/Wanggcong/Spatial-Temporal-Re-identification/blob/master/evaluate_st.py#L72](url)

Any help would be appreciated!

**Comment by Wanggcong** [comment]
I just follow [repos](https://github.com/layumi/Person_reID_baseline_pytorch) . As a simple suggestion, I think AP is computed like the precision-recall curve,  PR.

```
for i in range(ngood):
        d_recall = 1.0/ngood
        precision = (i+1)*1.0/(rows_good[i]+1)
        if rows_good[i]!=0:
            old_precision = i*1.0/rows_good[i]
        else:
            old_precision=1.0

        ap = ap + d_recall*(old_precision + precision)/2
```

1) plot the precision-recall point 
2)  compute the area : d_recall*(old_precision + precision)/2`
3)  sum all of small areas （thinking of calculus, the area of the precision-recall curve is mAP）.


It is just a coarse explanation. You can ask the author of the original repos for the detail.

**Comment by jerryhitit** [comment]
Thanks for your advice!

There is a detail explanation about this code in the [original repo](https://github.com/layumi/Person_reID_baseline_pytorch/issues/110)
