### ISSUE TITLE
Smoothing in the Joint Metric

### ISSUE THREAD

**Issue by jimbojumbo** [Wanggcong/Spatial-Temporal-Re-identification#22]
Hi, thanks for the great work and sharing the code!

May I ask which part of the code reflects your two observations mentioned in the paper, the Laplace smooth and Logistic function used to filter the visual and temporal information, I have some difficulties locate those implementations, thank you!

**Comment by jimbojumbo** [comment]
Found the Logistic smoothing, still have difficulties find Laplace smoothing

**Comment by AnonymousAuthorsCode** [comment]
> Found the Logistic smoothing, still have difficulties find Laplace smoothing

No laplace smoothing in this paper. It is just an observation in machine learning.

**Comment by Wanggcong** [comment]
No Laplace  smoothing in this paper. It is just an observation in machine learning. Logistic smoothing shares similar idea with Laplace smoothing, which is used to adjust the probability of rare (but not impossible).

**Comment by jimbojumbo** [comment]
Thanks for the explanation!
