### ISSUE TITLE
Visual stream features vs Spatial-Temporal stream

### ISSUE THREAD

**Issue by saif86** [Wanggcong/Spatial-Temporal-Re-identification#28]
Hello. Pretty nice and well coded repo. Thanks for your contributions. I have a question regarding feature extractions. For visual stream you are extracting gallery and query features after training the model. But for Spatial-Temporal stream, you are extracting distribution from training set data(camID+frames+labels). Shouldn't it be from gallery/query set? Because later you are joining those features. Please explain I have a little confusion. Many thanks

**Comment by Wanggcong** [comment]
--For Spatial-Temporal stream, you are extracting distribution from training set data(camID+frames+labels)?
Yes!
Shouldn't it be from gallery/query set?
--No. We assume the examples of training/gallery/query sets are drawn from the same distributions.

**Comment by saif86** [comment]
OK! Thanks a lot for your quick reply.
