### ISSUE TITLE
Making sense of `dict_cam_seq_max` dictionary in prepare_data.py

### ISSUE THREAD

**Issue by SurajDonthi** [Wanggcong/Spatial-Temporal-Re-identification#34]
Hi,

I was working with your code & was not able to make sense of where you obtained the sequence of values in `dict_cam_seq_max` in `parse_frames()` function in the prepare_data.py file. Can you mention the logic behind the sequence of values?

Thanks.

**Comment by Wanggcong** [comment]
This issue has been asked in [this link](https://github.com/Wanggcong/Spatial-Temporal-Re-identification/issues/10#issue-467686204). I hope this can help you!
