### ISSUE TITLE
Why use both "test" and "generate st model" mothed?

### ISSUE THREAD

**Issue by minygd** [Wanggcong/Spatial-Temporal-Re-identification#5]
Sorry to bother U. It confused me that the code of the two method are same, and what would possibly happened when I don't apply either of them? In another words, I want to know the effect of each method, Thx!

**Comment by minygd** [comment]
I find the way. There is a small bug in your README file.
That is, in "generate st model" part, the Python file is "gen_st_model_market.py".

**Comment by minygd** [comment]
Hello! I found that you have update the README file a week ago, but to my confused, you didn't fix it, though.
There is a small error in README file, while in the DukeMTMC-reID part is right, 'generate the st model for market ', the commend must be: 
python3 gen_st_model_market.py --name ft_ResNet50_pcb_market_e --data_dir "/home/huangpg/st-reid/dataset/market_rename/"

Thx.

**Comment by Wanggcong** [comment]
Hi,
  
 Thanks for pointing this.
  
 Guangcong
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Yang Zhou"<notifications@github.com>;
 发送时间: 2019年4月26日(星期五) 上午7:53
 收件人: "Wanggcong/Spatial-Temporal-Re-identification"<Spatial-Temporal-Re-identification@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: Re: [Wanggcong/Spatial-Temporal-Re-identification] Why use both"test" and "generate st model" mothed? (#5)

 

 
Hello! I found that you have update the README file a week ago, but to my confused, you didn't fix it, though.
There is a small error in README file, while in the DukeMTMC-reID part is right, 'generate the st model for market ', the commend must be:
python3 gen_st_model_market.py --name ft_ResNet50_pcb_market_e --data_dir "/home/huangpg/st-reid/dataset/market_rename/"
 
Thx.
