### ISSUE TITLE
basic information question

### ISSUE THREAD

**Issue by Adorablepet** [Wanggcong/Spatial-Temporal-Re-identification#9]
Q1. The model we train is only about visual features. The st model is a pytorch_result2.mat file.There is no training model that combines visual features and st.
Q2.Market1501 datasets has 6 cameras, DukeMTMC-reID datasets has 8 cameras, why is np.zeros ((class_num,8)) created in line 51 of the gen_st_model_market.py file?
market: 1->2 1->3 1->4 1->5 1->6
duke: 1->2 1->3 1->4 1->5 1->6 1->7 1->8
Q3: Is pytorch_result2.mat fixed for the dataset? Is the visual model one-to-one with it? Suppose I need to use the PCB model of the trained market dataset, then I can only call the corresponding pytorch_result2.mat ?
Thanks!

**Comment by Adorablepet** [comment]
Q2: Market1501 datasets has 6 cameras

**Comment by Wanggcong** [comment]
Q1：In evaluate_st.py.
Q2:  Should be np.zeros ((class_num,6)) on Market1501, but this does not affect the results. We will fix this bug. Thank you for pointing this.
Q3:  Yes. This is because different scenarios/datasets have different spatial-temporal distributions.

I hope my answer helps you.

**Comment by Adorablepet** [comment]
@Wanggcong I trained and tested on the market data under pytorch1.0.1 and 0.4.1 respectively(~0.1%). I found that the results I got were different from the papers, especially on the duke dataset. I think this should be related to the training strategy, is it not? There is a difference between the parameters of the training and the published parameters. I think you can clone the code and run it according to the parameters you provided. Is the result similar to mine, solve my doubts, thank you.

dukemtmc+RE: map:83.5% top-1:94.3%
dukemtmc+RE+re-rank: map:91.3% top-1:92.3%

market+RE: map:87.3% top-1:96.7%
market+RE+re-rank:map:94.5% top-1:96.8%

Thanks!

**Comment by Wanggcong** [comment]
In gen_st_model_market.py,  we added Line 68~69. In gen_st_model_duke.py,  these are no such bugs. 

                if spatial_temporal_count[i][j]==0 or spatial_temporal_count[i][k]==0:
                    continue 

After adding these lines, the performance will be close to ~98% top-1. We hope these can help you.
